[package]
name = "tag-finder"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.4"
clap = { version = "4.4", features = ["derive"] }
regex = "1.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"