[scan]
exclude_dirs = ["node_modules", "dist", ".git", ".vscode", ".idea", ".angular", "build", "target", "backend"]
include_extensions = ["html", "js", "jsx", "ts", "tsx", "php", "rs"]
css_extensions = ["css", "scss"]