[scan]
exclude_dirs = ["node_modules", "dist", ".git", ".vscode", ".idea", ".angular", "build", "target"]
include_extensions = ["html", "js", "jsx", "ts", "tsx", "php"]
css_extensions = ["css", "scss"]